### ISSUE TITLE
Upgrading to sylius version 1.11.0-dev 

### ISSUE THREAD

**Issue by tsogoo** [davidroberto/-NOT-MAINTAINED-SyliusExtraApiPlugin#5]
Hi. If you create new branch for sylius version 1.11.0-dev. I'm happy to push my upgraded code. It's not complete but has some progress.

**Comment by davidroberto** [comment]
Nice! I noticed also that some of the api endpoints / filters i added in the plugin are not necessary anymore with the new sylius versions, i'll check that

**Comment by davidroberto** [comment]
Here you go :) 

https://github.com/davidroberto/SyliusExtraApiPlugin/tree/release/v1.1.0
